sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - EXECUTE_CS_CHECK=true

before_script:
  - composer self-update
  - composer install --prefer-source --no-scripts

script:
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/phpcs ; fi

notifications:
  email: true
